storage:
  # OPENAI_API_TYPE : "azure"
  OPENAI_API_BASE : "https://aesopenai.openai.azure.com"
  OPENAI_API_KEY : "eea6e96919914989a60244c3a74c84f0"
  OPENAI_API_VERSION : "2024-08-01-preview"
  OPENAI_API_DEPLOYMENT : "gpt-4o-mini"
  # OPENAI_API_MODEL : "gpt-4o-mini"